### Comparisons among different QC methods, which include 
# Raw data
# Hybnorm only
# Hybnorm only + ComBat
# “Full norm”, i.e. using tranche 1 calibrators for both tranches
# Full norm + ComBat
# Darryl norm (i.e. SomaLogic’s new normalization)
# Darryl norm + ComBat

library(readxl) 
library(SomaDataIO)
source("QCnormTranche2.R")
library(sva)
library(umap)
library(GGally)
library(factoextra)

### load in the stored data for convenience
# normList = readRDS("normList.rds")
# RawM1 = normList$RawM1
# RawM2 = normList$RawM2
# TestRaw = normList$TestRaw
# MySoma1Hyb = normList$MySoma1Hyb
# MySoma2Hyb = normList$MySoma2Hyb
# TestHyb = normList$TestHyb
# TestHybCombat = normList$TestHybCombat
# MySoma1Full = normList$MySoma1Full
# MySoma2Full = normList$MySoma2Full
# TestMyFullOnly = normList$TestMyFullOnly
# TestMyFullCombat = normList$TestMyFullCombat
# Soma1 = normList$Soma1
# Soma2 = normList$Soma2
# TestSomaOnly = normList$TestSomaOnly
# TestSomaCombat = normList$TestSomaCombat

### source document required for running this script.
myFilePath <- "/Users/ydeng/Documents/QCstepOA/normComp/"  ### set required file directory
inputfile1 <- paste(myFilePath,"SS-200008.ADat",sep="") ### RawM1: Raw RFUs of tranche1
inputfile2 <- paste(myFilePath,"SS-205086.adat",sep="") ###RawM2: Raw RFUs of tranche2 
inputfile12 <- paste(myFilePath,"SS-200008.hybNorm.medNormInt.plateScale.medNormRefSMP.ADat",sep="") ### adat file whose colmeta provides references for malformations
inputfile3 <- paste(myFilePath,"SS-200008_v4_SynovialFluid.hybNormRef.medNormInt.plateScale.calibrate.20211007.adat",sep="") ### Soma1: normalized RFUs of tranche1 by somalogic 
inputfile4 <- paste(myFilePath,"SS-205086_v4_SynovialFluid.hybNormRef.medNormInt.plateScale.calibrate.20211007.adat",sep="")  ###Soma2: normliased RFUs of tranche2 by somalogic
clinicFile <- paste(myFilePath,"STEpUP_QCData_Tranche1.xlsx",sep="")  ### clinical file include matching step up id, disease group...
immunoFile <- paste(myFilePath,"1_Master list_analyte concentrations.xlsx",sep="") ### file includes external immuno essay measurements.
# pdf(file = "/Users/ydeng/Documents/QCstepOA/normComp/normPlot.pdf") ### pdf contains plots generated by this script


### retrieve RFUS from adat file
RawM1 = read.adat(inputfile1)
RawM2 = read.adat(inputfile2)
Soma1 = read.adat(inputfile3)
Soma2 = read.adat(inputfile4)
ColTable = initQCnorm(inputfile1,inputfile12) ### initialize meta data using function initQCnorm ### change to use attr(read.adat(inputfile12),"Col.Meta") as Luke suggested

### full normalisation. Funlist: defines normliastion steps in order. UserNorm: self defined function to process normalisation
Funlist1 = list(HYBNORM,MIDNORMcali,PLATESCALE,CALIBRATION) 
MySoma1Full = UserNorm(Funlist1,RawM1)
MySoma2Full = UserNorm(Funlist1,RawM2)
# MySoma1FullLog = UserNorm(Funlist1,log(RawM1)) ### log transformed RFU before normalization steps
# MySoma2FullLog = UserNorm(Funlist1,log(RawM2))

### hybnorm only normalisation
Funlist2 = list(HYBNORM)
MySoma1Hyb = UserNorm(Funlist2,RawM1)
MySoma2Hyb = UserNorm(Funlist2,RawM2)

### compare our normalisation and soma new normalisation (2021.10.08). 
### CompTWO: self written function, easily compare any two RFUs retrieved from adat files. 
### CompTWO input: RFU data frames, correlation coefficient threshold. Output: rownames and colnames not exist in both inputs; plots showing correlation; protein names with correlaiton coefficient below the input threshold. 
CompTWO(Soma1,MySoma1Full,0.9)
CompTWO(Soma2,MySoma2Full,0.9)
CompTWO(Soma1,MySoma1Hyb,0.7)
CompTWO(Soma2,MySoma2Hyb,0.7)

# SomaId of new normliased version (2021.10.08) are not consistent with previous version(2020.07.08) either.
# SomaId1 = attributes(Soma1)$Col.Meta["SomaId"]
# SomaId2 = attributes(RawM1)$Col.Meta["SomaId"]
# identical(SomaId1,SomaId2)
# changeOrder = vector()
# SomaIDKK=1
# notMatchSomaID=vector()
# for (k in 1:nrow(SomaId2)){
#   if(!any(which(as.matrix(SomaId1[,1]) %in% SomaId2[k,1]))){notMatchSomaID[SomaIDKK] = k
#   SomaIDKK=SomaIDKK+1}
#   else{changeOrder[k] = which(as.matrix(SomaId1[,1]) %in% SomaId2[k,1])}
# }
# SomaId2[notMatchSomaID,1]


### process two tranches for combined data set for batch test -> PCA|UMAP regarding to batches -> KNN test 
### For different input two tranches of data, the combat+PCA|UMAP+KNN test procedures are exactly the same,
###so only the first senario of combined raw data has detailed explanations for the necessary code blocks.

# 1. combined Raw data for batch test
TestRaw <- MyCombat(RawM1,RawM2,1) ### input two RFU matrix, the third argument means whether or not combat correction (1 means noCombat).###TestRaw is the processed combined RFUs after combat correction, only contain human sample and human proteins.
CombinedRaw = TestRaw[,which(colnames(TestRaw)=="CRYBB2.10000.28"):ncol(TestRaw)] ###combined expression data
batchMeta_Raw = TestRaw[,c("Tranche Batch","Plate Batch")]
# KNN1 <- KNNtest(CombinedRaw,batchMeta_Raw,3,2) ### 3 rounds, 4 mins. increasing rounds cost exponetial time but not too much change as 2. So 2 rounds is enough.

gp1<- PlotPCA(CombinedRaw,batchMeta_Raw,3,1,"PCA on combined raw data") ### 20 seconds to run this line. "prcomp" need to perform for each input exprDat, so I currently decide still to not put prcomp in the main body
gp2 <- PlotPCA(CombinedRaw,batchMeta_Raw,3,2,"PCA on combined raw data") ### compute prcomp one more time, which is not very long, but the code in the main body is much simpler. 
gp3 <- PlotUmap(CombinedRaw,batchMeta_Raw,1,"UMAP on combined raw data") ### 20 seconds to run this line. have not put umap() function in the main body, cost the time to calculate umap once more (not very long), but simplify the main body greatly.
gp4 <- PlotUmap(CombinedRaw,batchMeta_Raw,2,"UMAP on combined raw data")

CVlist1 <- CVbreak(RawM1,RawM2,"OA",CombinedRaw,"combined raw data") ###CV test for OA group: accorss/within place CV, accross/within tranche CV.
accrossPlateCV1 <- CVlist1[[1]] 
withinPlateCV1 <- CVlist1[[2]]
accrossTrancheCV1 <- CVlist1[[3]]
withinTrancheCV1 <- CVlist1[[4]]
# CVlist1 <- CVbreak(RawM1,RawM2,"INJ",CombinedRaw,"combined raw data") ### CV test for INJ group. To avoid to many variables need to define in the main body, currently comment of injury group, but the CV test running procedure is exactly as OA group

print("RawM1 accuracy against external controls")
exOA1 <- ExtVal(RawM1,"OA",clinicFile,immunoFile) ### Correlation table between somalogic measure and external immunoassay measures, for OA group
exINJ1 <- ExtVal(RawM1,"INJ",clinicFile,immunoFile) ### correlation table for Injury patients

VarOA1 <- VarExp("OA",RawM1,"RawM1") ### variance explained by OA replicates for tranche 1 data.
R2repeats(VarOA1,exOA1,"OA","RawM1") ### predicted R2 and actural R2, plot for OA group
VarINJ1 <- VarExp("INJ",RawM1,"RawM1") ### variance explained by Injury replicates for tranche 1 data.
R2repeats(VarINJ1,exINJ1,"INJ","RawM1") ### predicted R2 and actural R2, plot for injury group

# 2. Hybnorm only on individual tranche and then combine for batch test
TestHyb <- MyCombat(MySoma1Hyb,MySoma2Hyb,1) ### without combat
CombinedHyb = TestHyb[,which(colnames(TestHyb)=="CRYBB2.10000.28"):ncol(TestHyb)] 
batchMeta_HybOnly = TestHyb[,c("Tranche Batch","Plate Batch")]
# KNN2 <- KNNtest(CombinedHyb,batchMeta_HybOnly,3,2)

gp5 <- PlotPCA(CombinedHyb,batchMeta_HybOnly,3,1,"PCA on combined hyb only data")
gp6 <- PlotPCA(CombinedHyb,batchMeta_HybOnly,3,2,"PCA on combined hyb only data")
gp7 <- PlotUmap(CombinedHyb,batchMeta_HybOnly,1,"UMAP on combined hyb only data")
gp8 <- PlotUmap(CombinedHyb,batchMeta_HybOnly,2,"UMAP on combined hyb only data")

CVlist2 <-CVbreak(MySoma1Hyb,MySoma2Hyb,"OA",CombinedHyb,"combined hyb only data")
accrossPlateCV2 <- CVlist2[[1]]
withinPlateCV2 <- CVlist2[[2]]
accrossTrancheCV2 <- CVlist2[[3]]
withinTrancheCV2 <- CVlist2[[4]]
# CVlist2 <-CVbreak(MySoma1Hyb,MySoma2Hyb,"INJ",CombinedHyb,"combined hyb only data")

print("MySoma1Hyb accuracy against external controls")
exOA2 <-ExtVal(MySoma1Hyb,"OA",clinicFile,immunoFile)
exINJ2 <- ExtVal(MySoma1Hyb,"INJ",clinicFile,immunoFile)

VarOA2 <- VarExp("OA",MySoma1Hyb,"MySoma1Hyb")
R2repeats(VarOA2,exOA2,"OA","MySoma1Hyb")
VarINJ2 <- VarExp("INJ",MySoma1Hyb,"MySoma1Hyb")
R2repeats(VarINJ2,exINJ2,"INJ","MySoma1Hyb")

# 3. Hybnorm only + ComBat  ### 0 means no further combat after normalisation on individual tranche; 1 means further combat applied
TestHybCombat <- MyCombat(MySoma1Hyb,MySoma2Hyb,0)
combat_MySomaHyb <- TestHybCombat[,which(colnames(TestHybCombat)=="CRYBB2.10000.28"):ncol(TestHybCombat)]
batchMeta_MySomaHyb = TestHybCombat[,c("Tranche Batch","Plate Batch")]
# KNN3 <- KNNtest(combat_MySomaHyb,batchMeta_MySomaHyb,3,2)

gp9 <- PlotPCA(combat_MySomaHyb,batchMeta_MySomaHyb,3,1,"PCA on combat_MySomaHyb")
gp10 <- PlotPCA(combat_MySomaHyb,batchMeta_MySomaHyb,3,2,"PCA on combat_MySomaHyb")
gp11 <- PlotUmap(combat_MySomaHyb,batchMeta_MySomaHyb,1,"UMAP on combat_MySomaHyb")
gp12 <- PlotUmap(combat_MySomaHyb,batchMeta_MySomaHyb,2,"UMAP on combat_MySomaHyb")

CVlist3 <- CVbreak(MySoma1Hyb,MySoma2Hyb,"OA",combat_MySomaHyb,"combat_MySomaHyb")
accrossPlateCV3 <- CVlist3[[1]] 
withinPlateCV3 <- CVlist3[[2]]
accrossTrancheCV3 <- CVlist3[[3]]
withinTrancheCV3 <- CVlist3[[4]]
# CVlist3 <- CVbreak(MySoma1Hyb,MySoma2Hyb,"INJ",combat_MySomaHyb,"combat_MySomaHyb")

print("combat_MySomaHyb accuracy against external controls")
exOA3 <- ExtVal(extractTrancheX(MySoma1Hyb,combat_MySomaHyb,1),"OA",clinicFile,immunoFile)
exINJ3 <- ExtVal(extractTrancheX(MySoma1Hyb,combat_MySomaHyb,1),"INJ",clinicFile,immunoFile)


### extractTrancheX: self written function, conveniently retrieve processed tranches of data.
VarOA3 <- VarExp("OA",extractTrancheX(MySoma1Hyb,combat_MySomaHyb,1),"MySoma1Hyb+combat")
R2repeats(VarOA3,exOA3,"OA","MySoma1Hyb+combat")
VarINJ3 <- VarExp("INJ",extractTrancheX(MySoma1Hyb,combat_MySomaHyb,1),"MySoma1Hyb+combat")
R2repeats(VarINJ3,exINJ3,"INJ","MySoma1Hyb+combat")
# VarOA3 <- VarExp("OA",extractTrancheX(MySoma2Hyb,combat_MySomaHyb,2),"MySoma2Hyb+combat")
# VarINJ3 <- VarExp("INJ",extractTrancheX(MySoma2Hyb,combat_MySomaHyb,2),"MySoma2Hyb+combat")

# “Full norm”, i.e. using tranche 1 calibrators for both tranches, then combine full normed two tranches for batch test
TestMyFullOnly <- MyCombat(MySoma1Full,MySoma2Full,1)
MyFullOnly <- TestMyFullOnly[,which(colnames(TestMyFullOnly)=="CRYBB2.10000.28"):ncol(TestMyFullOnly)] 
batchMeta_MyFullOnly = TestMyFullOnly[,c("Tranche Batch","Plate Batch")]
# KNN4 <- KNNtest(MyFullOnly,batchMeta_MyFullOnly,3,2)

gp13 <- PlotPCA(MyFullOnly,batchMeta_MyFullOnly,3,1,"PCA on combined my full norm")  ###PCA and UMAP plot
gp14 <- PlotPCA(MyFullOnly,batchMeta_MyFullOnly,3,2,"PCA on combined my full norm")
gp15 <- PlotUmap(MyFullOnly,batchMeta_MyFullOnly,1,"UMAP on combined my full norm")
gp16 <- PlotUmap(MyFullOnly,batchMeta_MyFullOnly,2,"UMAP on combined my full norm")

CVlist4 <- CVbreak(MySoma1Full,MySoma2Full,"OA",MyFullOnly,"combined my full norm")
accrossPlateCV4 <- CVlist4[[1]] 
withinPlateCV4 <- CVlist4[[2]]
accrossTrancheCV4 <- CVlist4[[3]]
withinTrancheCV4 <- CVlist4[[4]]
# CVlist4 <- CVbreak(MySoma1Full,MySoma2Full,"INJ",log(MyFullOnly),"combined my full norm")

print("MySoma1Full accuracy against external controls")
exOA4 <- ExtVal(MySoma1Full,"OA",clinicFile,immunoFile)
exINJ4 <- ExtVal(MySoma1Full,"INJ",clinicFile,immunoFile)

VarOA4 <- VarExp("OA",MySoma1Full,"MySoma1Full")
R2repeats(VarOA4,exOA4,"OA","MySoma1Full")
VarINJ4 <- VarExp("INJ",MySoma1Full,"MySoma1Full")
R2repeats(VarINJ4,exINJ4,"INJ","MySoma1Full")

# 5. Full norm + ComBat
TestMyFullCombat <- MyCombat(MySoma1Full,MySoma2Full,0)
combat_MySomaFull <- TestMyFullCombat[,which(colnames(TestMyFullCombat)=="CRYBB2.10000.28"):ncol(TestMyFullCombat)] 
batchMeta_MySomaFul = TestMyFullCombat[,c("Tranche Batch","Plate Batch")]
# KNN5<- KNNtest(combat_MySomaFull,batchMeta_MySomaFul,3,2)

gp17 <- PlotPCA(combat_MySomaFull,batchMeta_MySomaFul,3,1,"PCA on combat_MySomaFul")
gp18 <- PlotPCA(combat_MySomaFull,batchMeta_MySomaFul,3,2,"PCA on combat_MySomaFul")
gp19 <- PlotUmap(combat_MySomaFull,batchMeta_MySomaFul,1,"UMAP on combat_MySomaFul")
gp20 <- PlotUmap(combat_MySomaFull,batchMeta_MySomaFul,2,"UMAP on combat_MySomaFul")

CVlist5 <- CVbreak(MySoma1Full,MySoma2Full,"OA",combat_MySomaFull,"combat_MySomaFul")
accrossPlateCV5 <- CVlist5[[1]] 
withinPlateCV5 <- CVlist5[[2]]
accrossTrancheCV5 <- CVlist5[[3]]
withinTrancheCV5 <- CVlist5[[4]]
# CVlist5 <- CVbreak(MySoma1Full,MySoma2Full,"INJ",combat_MySomaFull,"combat_MySomaFul")

print("combat_MySomaFul accuracy against external controls")
exOA5 <-  ExtVal(extractTrancheX(MySoma1Full,combat_MySomaFull,1),"OA",clinicFile,immunoFile)
exINJ5 <- ExtVal(extractTrancheX(MySoma1Full,combat_MySomaFull,1),"INJ",clinicFile,immunoFile)

VarOA5 <- VarExp("OA",extractTrancheX(MySoma1Full,combat_MySomaFull,1),"MySoma1Full+combat")
R2repeats(VarOA5,exOA5,"OA","MySoma1Full+combat")
VarINJ5 <- VarExp("INJ",extractTrancheX(MySoma1Full,combat_MySomaFull,1),"MySoma1Full+combat")
R2repeats(VarINJ5,exINJ5,"INJ","MySoma1Full+combat")
# VarOA5 <- VarExp("OA",extractTrancheX(MySoma2Full,combat_MySomaFull,2),"MySoma1Full+combat")
# VarINJ5 <- VarExp("INJ",extractTrancheX(MySoma2Full,combat_MySomaFull,2),"MySoma1Full+combat")

# 6. Darryl norm (i.e. SomaLogic’s new normalization). Combine somalogic normliased two tranches data for batch test.
TestSomaOnly <- MyCombat(Soma1,Soma2,1)
SomaOnly = TestSomaOnly[,which(colnames(TestSomaOnly)=="CRYBB2.10000.28"):ncol(TestSomaOnly)] 
batchMeta_SomaOnly = TestSomaOnly[,c("Tranche Batch","Plate Batch")]
# KNN6 <- KNNtest(SomaOnly,batchMeta_SomaOnly,3,2)

gp21 <- PlotPCA(SomaOnly,batchMeta_SomaOnly,3,1,"PCA on combined Soma Only")
gp22 <- PlotPCA(SomaOnly,batchMeta_SomaOnly,3,2,"PCA on combined Soma Only")
gp23 <- PlotUmap(SomaOnly,batchMeta_SomaOnly,1,"UMAP on combined Soma Only")
gp24 <- PlotUmap(SomaOnly,batchMeta_SomaOnly,2,"UMAP on combined Soma Only")

CVList6 <- CVbreak(Soma1,Soma2,"OA",SomaOnly,"combined Soma Only")
accrossPlateCV6 <- CVlist6[[1]] 
withinPlateCV6 <- CVlist6[[2]]
accrossTrancheCV6 <- CVlist6[[3]]
withinTrancheCV6 <- CVlist6[[4]]
# CVList6 <- CVbreak(Soma1,Soma2,"INJ",SomaOnly,"combined Soma Only")

print("SomaOnly accuracy against external controls")
exOA6 <- ExtVal(Soma1,"OA",clinicFile,immunoFile)
exINJ6 <- ExtVal(Soma1,"INJ",clinicFile,immunoFile)

VarOA6 <- VarExp("OA",Soma1,"Soma1")
R2repeats(VarOA6,exOA6,"OA","Soma1")
VarINJ6 <- VarExp("INJ",Soma1,"Soma1")
R2repeats(VarINJ6,exINJ6,"INJ","Soma1")

#7.  Darryl norm + ComBat. combine somalogic normalised data and furhter combat correction for batch test.
TestSomaCombat <- MyCombat(Soma1,Soma2,0)
combat_Soma = TestSomaCombat[,which(colnames(TestSomaCombat)=="CRYBB2.10000.28"):ncol(TestSomaCombat)]  
batchMeta_Soma = TestSomaCombat[,c("Tranche Batch","Plate Batch")]
# KNN7 <- KNNtest(combat_Soma,batchMeta_Soma,3,2)

gp25 <- PlotPCA(combat_Soma,batchMeta_Soma,3,1,"PCA on combat_Soma")
gp26 <- PlotPCA(combat_Soma,batchMeta_Soma,3,2,"PCA on combat_Soma")
gp27 <- PlotUmap(combat_Soma,batchMeta_Soma,1,"UMAP on combat_Soma")
gp28 <- PlotUmap(combat_Soma,batchMeta_Soma,2,"UMAP on combat_Soma")

CVlist7 <- CVbreak(Soma1,Soma2,"OA",combat_Soma,"combat_Soma")
accrossPlateCV7 <- CVlist7[[1]] 
withinPlateCV7 <- CVlist7[[2]]
accrossTrancheCV7 <- CVlist7[[3]]
withinTrancheCV7 <- CVlist7[[4]]
CVbreak(Soma1,Soma2,"INJ",combat_Soma,"combat_Soma")

print("combat_Soma accuracy against external controls")
exOA7 <- ExtVal(extractTrancheX(Soma1,combat_Soma,1),"OA",clinicFile,immunoFile)
exINJ7 <- ExtVal(extractTrancheX(Soma1,combat_Soma,1),"INJ",clinicFile,immunoFile)

VarOA7 <- VarExp("OA",extractTrancheX(Soma1,combat_Soma,1),"Soma1+combat")
R2repeats(VarOA7,exOA7,"OA","Soma1+combat")
VarINJ7 <- VarExp("INJ",extractTrancheX(Soma1,combat_Soma,1),"Soma1+combat")
R2repeats(VarINJ7,exINJ7,"INJ","Soma1+combat")

# 8. log + “Full norm”, i.e. using tranche 1 calibrators for both tranches. Log transform on raw RFUs before normalisation
# TestMyFullLogOnly <- MyCombat(MySoma1FullLog,MySoma2FullLog,1)
# MyFullLogOnly <- TestMyFullLogOnly[,which(colnames(TestMyFullLogOnly)=="CRYBB2.10000.28"):ncol(TestMyFullLogOnly)]  
# batchMeta_MyFullLogOnly = TestMyFullLogOnly[,c("Tranche Batch","Plate Batch")]
# # KNNtest(MyFullLogOnly,batchMeta_MyFullLogOnly,2,2)
# 
# PlotPCA(MyFullLogOnly,batchMeta_MyFullLogOnly,3,1,"PCA on combined my full norm on log RFU")  ###PCA and UMAP plot
# PlotPCA(MyFullLogOnly,batchMeta_MyFullLogOnly,3,2,"PCA on combined my full norm on log RFU")
# PlotUmap(MyFullLogOnly,batchMeta_MyFullLogOnly,1,"UMAP on combined my full norm on log RFU")
# PlotUmap(MyFullLogOnly,batchMeta_MyFullLogOnly,2,"UMAP on combined my full norm on log RFU")
# 
# CVbreak(MySoma1FullLog,MySoma2FullLog,"OA",MyFullLogOnly,"combined my full norm on log RFU")
# CVbreak(MySoma1FullLog,MySoma2FullLog,"INJ",MyFullLogOnly,"combined my full norm on log RFU")
# 
# print("MySoma1FullLog accuracy against external controls")
# exOA8 <- ExtVal(MySoma1FullLog,"OA",clinicFile,immunoFile)
# exINJ8 <- ExtVal(MySoma1FullLog,"INJ",clinicFile,immunoFile)
# 
# VarOA8 <- VarExp("OA",MySoma1FullLog,"MySoma1FullLog")
# R2repeats(VarOA8,exOA8,"OA","MySoma1FullLog")
# VarINJ8 <- VarExp("INJ",MySoma1FullLog,"MySoma1FullLog")
# R2repeats(VarINJ8,exINJ8,"INJ","MySoma1FullLog")
# 
# # 9. log + Full norm + ComBat
# TestFullLogCombat <- MyCombat(MySoma1FullLog,MySoma2FullLog,0)
# combat_MySomaFullLog <- TestFullLogCombat[,which(colnames(TestFullLogCombat)=="CRYBB2.10000.28"):ncol(TestFullLogCombat)]  
# batchMeta_MySomaFullLog = TestFullLogCombat[,c("Tranche Batch","Plate Batch")]
# # KNNtest(combat_MySomaFullLog,batchMeta_MySomaFullLog,2,2)
# 
# PlotPCA(combat_MySomaFullLog,batchMeta_MySomaFullLog,3,1,"PCA on combatted my full norm on log RFU")  ###PCA and UMAP plot
# PlotPCA(combat_MySomaFullLog,batchMeta_MySomaFullLog,3,2,"PCA on combatted my full norm on log RFU")
# PlotUmap(combat_MySomaFullLog,batchMeta_MySomaFullLog,1,"UMAP on combatted my full norm on log RFU")
# PlotUmap(combat_MySomaFullLog,batchMeta_MySomaFullLog,2,"UMAP on combatted my full norm on log RFU")
# 
# exOA9 <- CVbreak(MySoma1FullLog,MySoma2FullLog,"OA",combat_MySomaFullLog,"combatted my full norm on log RFU")
# exINJ9 <-CVbreak(MySoma1FullLog,MySoma2FullLog,"INJ",combat_MySomaFullLog,"combatted my full norm on log RFU")
# 
# print("Combatted MySoma1FullLog accuracy against external controls")
# cutCombat_MyFullCombat = MySoma1FullLog[which(grepl("Sample",MySoma1FullLog[,"SampleType"])),1:(which(colnames(MySoma1FullLog)=="CRYBB2.10000.28")-1)]
# ExtVal(cbind(cutCombat_MyFullCombat,combat_MySomaFullLog[1:nrow(cutCombat_MyFullCombat),]),"OA",clinicFile,immunoFile)
# ExtVal(cbind(cutCombat_MyFullCombat,combat_MySomaFullLog[1:nrow(cutCombat_MyFullCombat),]),"INJ",clinicFile,immunoFile)
# 
# VarOA9 <- VarExp("OA",cbind(cutCombat_MyFullCombat,combat_MySomaFullLog[1:nrow(cutCombat_MyFullCombat),]),"combatted my full norm on log RFU")
# R2repeats(VarOA9,exOA9,"OA","combatted my full norm on log RFU")
# VarINJ9 <- VarExp("INJ",cbind(cutCombat_MyFullCombat,combat_MySomaFullLog[1:nrow(cutCombat_MyFullCombat),]),"combatted my full norm on log RFU")
# R2repeats(VarINJ9,exINJ9,"INJ","combatted my full norm on log RFU")
# 
# dev.off()

# Raw data: RawM1,RawM2, CombinedRaw is the combined raw data.
# Hybnorm only: HubNorm only on seperate tranche individually: MySoma1Hyb, MySoma2Hyb; CombinedHyb is the expression profile of combined hyb normalised data.
# Hybnorm only + ComBat: combat_MySomaHyb is the expression profile by further combatted  on CombinedHyb.
# “Full norm”: full norm on seprate tranche individually: MySoma1Full,MySoma2Full; MyFullOnly is the expression profile of combined full normalised data.
# Full norm + ComBat: combat_MySomaFull is the expression profile by further combatted on MyFullOnly.
# Darryl norm: Daryyl normliased: Soma1,Soma2; SomaOnly is the expression profile of combined Soma1 and Soma2.
# Darryl norm + ComBat: combat_Soma is the expression profile by further combatted on SomaOnly.
# note that: combined data sets and combatted data sets only include human samples and human proteins.

# normList = list("RawM1"=RawM1,"RawM2"=RawM2,"TestRaw"=TestRaw,"KNN1"=KNN1,
#                 "MySoma1Hyb"=MySoma1Hyb,"MySoma2Hyb"=MySoma2Hyb,"TestHyb"=TestHyb,"KNN2"=KNN2, 
#                 "TestHybCombat"=TestHybCombat,"KNN3"=KNN3,
#                 "MySoma1Full"=MySoma1Full,"MySoma2Full"=MySoma2Full,"TestMyFullOnly"=TestMyFullOnly,"KNN4"=KNN4,
#                 "TestMyFullCombat"=TestMyFullCombat,"KNN5"=KNN5,
#                 "Soma1"=Soma1,"Soma2"=Soma2,"TestSomaOnly"=TestSomaOnly,"KNN6"=KNN6,
#                 "TestSomaCombat"=TestSomaCombat,"KNN7"=KNN7)
# saveRDS(normList,file="normList.rds")
save(gp1,gp2,gp3,gp4,gp5,gp6,gp7,gp8,gp9,gp10,gp11,gp12,gp13,gp14,gp15,gp16,gp17,gp18,gp19,gp20,gp21,gp22,gp23,gp24,gp25,gp26,gp27,gp28,file="myNormCompPlot.RData")


### plot external check among all normalisation choices.
externalCheck <- cbind(exOA1[,1:3],exOA2[,3],exOA3[,3],exOA4[,3],exOA5[,3],exOA6[,3],exOA7[,3]) ### for OA patients
# externalCheck <- cbind(exINJ1[,1:3],exINJ2[,3],exINJ3[,3],exINJ4[,3],exINJ5[,3],exINJ6[,3],exINJ7[,3]) ### for Injury patients

CorDatY = as.matrix(externalCheck[,3],ncol=1)
CorDatX = rep(as.matrix(externalCheck[,2],ncol=1),(ncol(externalCheck)-2))
CorC = rep(seq(1:(ncol(externalCheck)-2)),rep(nrow(externalCheck),ncol(externalCheck)-2))
for(k in 4:ncol(externalCheck)){
  CorDatY =  rbind(CorDatY,as.matrix(externalCheck[,k],ncol=1))
}
colnames(CorDatY) = "CorDatY"
CorDatP = as.data.frame(cbind(CorDatX,CorC,CorDatY))

xlabels=c("Raw","Hybnorm only","Hybnorm only + ComBat","Full norm","Full norm + ComBa","SomaLogic norm","SomaLogic norm + ComBat")

ggplot(data = CorDatP) + geom_line(aes(x=CorC,y=as.numeric(CorDatY),group=CorDatX,col=CorDatX)) + ggtitle("Correlation between RFUs and immunoassay for OA patients") +
  xlab("Normalisations") + ylab("Correlation coefficient") +labs(color = "SomaName") + scale_x_discrete(breaks=seq(1:7),labels=xlabels) + 
  theme(axis.text.x = element_text(size=6, angle=20),legend.title =element_text(size = 6), legend.text = element_text(size = 6),plot.title=element_text(size = 10,face="bold",hjust=0.5),
        axis.title.y =element_text(size=8),axis.title.x =element_text(size=8)) 

### following is to plot external check comparison for injury group. for simplicity to define variables, "plot external check" run from the "externalCheck <- " again for injury patients. 
ggplot(data = CorDatP) + geom_line(aes(x=CorC,y=as.numeric(CorDatY),group=CorDatX,col=CorDatX)) + ggtitle("Correlation between RFUs and immunoassay for Injury patients") +
  xlab("Normalisations") + ylab("Correlation coefficient") +labs(color = "SomaName") + scale_x_discrete(breaks=seq(1:7),labels=xlabels) +
  theme(axis.text.x = element_text(size=6, angle=20),legend.title =element_text(size = 6), legend.text = element_text(size = 6),plot.title=element_text(size = 10,face="bold",hjust=0.5),
        axis.title.y =element_text(size=8),axis.title.x =element_text(size=8))

VarExp("OA",TestRaw,"Combined raw two tranches for OA group")
VarExp("OA",TestHyb,"Combined hybnormed two tranches for OA group")
VarExp("OA",TestHybCombat,"Combined hybnormed and further combat corrected two tranches for OA group")
VarExp("OA",TestMyFullOnly,"Combined ful normed two tranches for OA group")
VarExp("OA",TestMyFullCombat,"Combined ful normed and further combat corrected two tranches for OA group")
VarExp("OA",TestSomaOnly,"Combined somologic normliased two tranches for OA group")
VarExp("OA",TestSomaCombat,"Combined somologic normliased and further combat corrected two tranches for OA group")

VarExp("INJ",TestRaw,"Combined raw two tranches for injury group")
VarExp("INJ",TestHyb,"Combined hybnormed two tranches for injury group")
VarExp("INJ",TestHybCombat,"Combined hybnormed and further combat corrected two tranches for injury group")
VarExp("INJ",TestMyFullOnly,"Combined ful normed two tranches for injury group")
VarExp("INJ",TestMyFullCombat,"Combined ful normed and further combat corrected two tranches for injury group")
VarExp("INJ",TestSomaOnly,"Combined somologic normliased two tranches for injury group")
VarExp("INJ",TestSomaCombat,"Combined somologic normliased and further combat corrected two tranches for injury group")








